import React from 'react'
import style from './About.module.css'
function About() {
  return (
    <>
      <div className={style.imageContanre}>
        <img src="/images/banner.jpg" alt="" />
      </div>
      <main className={style.main}>
        <h2 className={style.titel}>who we are</h2>
        <div className={style.contaner}>
          <img src="/images/yonas.jpg" alt="" />
          <p className={style.p1}>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, molestias dicta. Perferendis quos illo culpa voluptas necessitatibus sunt. Aperiam cupiditate suscipit harum optio iusto quisquam dolor adipisci! Modi nihil id tempore eum iure. Vitae reiciendis dolorem exercitationem deserunt sapiente nemo fugit temporibus suscipit aliquam ipsa mollitia eaque tempora natus, nesciunt illo in alias quae eum animi eligendi! Atque modi nihil minus dolores repellendus voluptatibus consequatur dolore quidem possimus suscipit ex quia ipsum, labore dignissimos error sequi beatae veniam vero voluptas adipisci! Temporibus quam reprehenderit labore cum et officiis magni harum, possimus autem earum voluptas repellendus ut corrupti dicta tempora numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas nostrum aperiam sed quaerat? Repudiandae nobis facilis ducimus eius harum. Fugit porro culpa nobis accusantium provident, quia perferendis cupiditate illo, error illum ut odio amet ea quam? Consequatur, nesciunt cupiditate at quisquam ullam aliquid corporis perspiciatis sunt ea laborum impedit laudantium.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente aut pariatur placeat! Nam repudiandae libero quae recusandae quia quam voluptates dolore ratione ex autem nostrum aperiam quasi alias, aliquid illo adipisci harum assumenda iure eaque unde aut doloribus. Debitis, aliquam cumque facere veniam, optio explicabo dolores voluptatibus ea qui, asperiores ipsum adipisci. Atque at officia laborum expedita nostrum consequuntur asperiores corrupti, odit provident ad impedit! Dolores sunt veniam earum saepe soluta odio, reprehenderit officiis nesciunt voluptatem corporis aperiam, exercitationem laudantium neque? Modi voluptatum labore, enim incidunt optio natus molestias aut quia! Culpa esse maiores enim facilis beatae laboriosam, quod ad iusto ab deleniti animi similique, eveniet ex explicabo quis id voluptatem provident alias unde laudantium delectus, quia perspiciatis ullam. Consequatur ipsam incidunt nihil esse ipsa exercitationem pariatur aperiam quidem reprehenderit commodi, impedit nemo quaerat velit, praesentium iste excepturi sunt fugiat blanditiis quos animi ducimus quisquam? Quo et ut exercitationem quis, illo sit cumque molestias, dignissimos odio deleniti facere nostrum tempora atque enim qui repellat dolorem provident quia eum! Rerum velit itaque, tempora eum quam, labore error repudiandae molestiae ipsa quaerat voluptate cum blanditiis exercitationem animi eius reprehenderit soluta quibusdam explicabo, fuga iste rem inventore veritatis reiciendis quo. Eos ipsum mollitia cumque aliquid neque architecto alias minima officiis sunt, assumenda voluptate labore atque corrupti voluptatem voluptates, inventore laudantium. Assumenda vel excepturi tenetur repellendus molestiae accusamus qui magnam beatae quisquam iure minus deserunt mollitia deleniti, delectus itaque non harum alias enim omnis odit ducimus ratione fugit amet. Explicabo, unde quaerat ullam illo temporibus, nobis eum quidem adipisci perspiciatis quia aspernatur ab est voluptatem inventore quae sed vitae quas assumenda placeat deleniti perferendis dolor. Temporibus eum recusandae odit labore necessitatibus veniam nesciunt rerum, doloremque, porro soluta unde blanditiis nisi ipsa, ex animi. Architecto praesentium illo maiores laborum ipsam, doloremque distinctio sequi velit. Dolor?
          </p>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis voluptatum laboriosam eveniet ad quam, provident adipisci molestias possimus consectetur corporis. Ipsum excepturi tempore ducimus perspiciatis animi sunt repellendus esse iste laudantium maxime in, enim debitis consequatur obcaecati deserunt aperiam corrupti, perferendis molestiae vel dicta laboriosam earum! Vitae velit fuga voluptates possimus, earum autem, maiores sint modi ab inventore delectus incidunt! Vitae provident dolorum suscipit, similique, odio nostrum distinctio harum eius, dicta modi veritatis temporibus minus eaque rem accusantium ipsam commodi ex nemo ab inventore aliquid porro. In optio voluptas eos harum quaerat quam ullam culpa praesentium quibusdam sunt dicta error laboriosam neque voluptatem, debitis, eveniet nam sit provident. Perferendis, quo! Beatae, placeat, officiis incidunt molestias quasi ad magnam tenetur quisquam ut animi repellat modi assumenda rem laboriosam quibusdam dicta ratione nihil expedita porro deserunt fugit cum perferendis. Reiciendis reprehenderit explicabo, officiis distinctio incidunt consectetur dolorum, sapiente sit nihil tenetur laborum temporibus est totam porro iure. Neque quam iste fuga  totam laboriosam explicabo? Vel esse facilis eius quos numquam necessitatibus optio impedit tempora sit praesentium quas, aperiam sed consectetur, at explicabo atque nihil voluptatem.</p>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique qui et, iure voluptatum dicta minima nemo distinctio, dignissimos ipsa explicabo non reprehenderit voluptatibus debitis eius pariatur suscipit laudantium quia commodi, officia porro sint ab! Earum quas voluptatum at quo aperiam facere architecto suscipit! Commodi velit consequuntur debitis saepe perspiciatis maxime molestias. In recusandae ab ex. Quo ipsam quam facilis modi totam incidunt laudantium exercitationem ab blanditiis a sequi, recusandae corporis rerum molestiae asperiores eligendi repellat ad in. Ipsa, corrupti? Quasi natus sequi temporibus mollitia voluptatem veniam aperiam laudantium reiciendis officia fuga aspernatur obcaecati corrupti, ut, quod quae autem sunt perferendis! Sapiente nemo laborum velit voluptatibus ad numquam debitis provident aliquam a corrupti dolor nesciunt soluta culpa doloribus atque eligendi quia, excepturi neque consequuntur? Ducimus recusandae magnam architecto quidem aut omnis suscipit? Dolor expedita atque a tempore laudantium modi facilis sunt quas omnis ut rem voluptatem, libero accusamus eligendi molestias quo quisquam necessitatibus cum in placeat aperiam! Exercitationem facere accusantium recusandae quidem molestias atque sint, harum excepturi explicabo architecto, rerum, magnam culpa eum? Similique libero ratione incidunt officiis aliquam eaque numquam laborum aut fuga saepe inventore delectus, facilis reiciendis quod minima voluptatum corrupti eveniet possimus ab assumenda cumque quo illum recusandae. Quos nesciunt repudiandae earum ipsum omnis accusamus, exercitationem atque nihil quia quod animi eligendi laudantium aperiam nulla? Sapiente voluptatem autem possimus facilis eaque ea, veritatis deserunt perferendis nesciunt voluptatibus! Iure animi sunt praesentium, perspiciatis itaque ipsum, enim a doloribus repellendus ratione quasi. Provident accusantium harum, illo, voluptatem, voluptatum culpa cupiditate vero voluptatibus doloremque ullam numquam tenetur! Illum quod debitis fugit, magnam ipsam harum repellendus at earum aspernatur cupiditate saepe vero iste molestias consequatur aperiam ab excepturi quibusdam quasi, nam quo modi possimus labore qui. Hic ullam vel, aliquam necessitatibus sed obcaecati et doloremque, nihil non tempora vitae similique, illum magnam?</p>
        </div>
      </main>
    </>

  )
}

export default About